version: '2.11'

services:
  db:
    build: .
    container_name: webcontacts-backend
    restart: always
    ports:
      - '5435:5432'
    volumes:
      - .docker/dbdata:/var/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=webcontacts_db
      - SECRET_KEY='my_secret_key'
      - EXPIRES_IN='30d'
